[network]
name = "devnet"
orchestrator_port = 20445
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_api_port = 20444
stacks_api_events_port = 20446
bitcoin_explorer_port = 8001
stacks_explorer_port = 8000
postgres_port = 5432
subnet_node_p2p_port = 30444
subnet_node_rpc_port = 30443
subnet_api_port = 13999
subnet_api_events_port = 30446
disable_stacks_api = false
disable_stacks_explorer = false
disable_bitcoin_explorer = true
enable_subnet_node = false
docker_host = "unix:///var/run/docker.sock"
use_docker_gateway_routing = true

[network.epoch_2_0]
start_height = 100

[network.epoch_2_05]
start_height = 102

[network.epoch_2_1]
start_height = 106

[network.epoch_2_2]
start_height = 110

[network.epoch_2_3]
start_height = 114

[network.epoch_2_4]
start_height = 118

[network.epoch_2_5]
start_height = 122

[network.epoch_3_0]
start_height = 126

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 10000000000000000

[accounts.wallet_1]
mnemonic = "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong"
balance = 10000000000000000

[accounts.wallet_2]
mnemonic = "legal winner thank year wave sausage worth useful legal winner thank yellow"
balance = 10000000000000000

[accounts.relayer]
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
balance = 10000000000000000
